SELECT cc.ID
FROM ECOLI_DATA cc
    INNER JOIN ECOLI_DATA c
    ON cc.PARENT_ID = c.ID
    INNER JOIN ECOLI_DATA p
    ON c.PARENT_ID = p.ID
    LEFT JOIN ECOLI_DATA pp
    ON p.PARENT_ID = pp.ID
WHERE pp.ID IS NULL
ORDER BY ID ASC;