WITH RENTING_CAR AS (
    SELECT c.CAR_ID, h.START_DATE, h.END_DATE
    FROM CAR_RENTAL_COMPANY_CAR c
        INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
        ON c.CAR_ID = h.CAR_ID
    WHERE c.CAR_TYPE in ('세단', 'SUV')
        AND h.START_DATE <= '2022-11-30'  -- 대여 기간이 11월과 겹치는 조건 수정
        AND h.END_DATE >= '2022-11-01'
),
RENTAL_FEE AS (
    SELECT c.CAR_ID, c.CAR_TYPE, 30 * c.DAILY_FEE * (100 - p.DISCOUNT_RATE) / 100 AS FEE
    FROM CAR_RENTAL_COMPANY_CAR c
        INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
        ON c.CAR_TYPE = p.CAR_TYPE
        AND p.DURATION_TYPE = '30일 이상'
    WHERE 30 * c.DAILY_FEE * (100 - p.DISCOUNT_RATE) / 100 >= 500000
        AND 30 * c.DAILY_FEE * (100 - p.DISCOUNT_RATE) / 100 <= 2000000
)
SELECT CAR_ID, CAR_TYPE, ROUND(FEE, 0) AS FEE
FROM RENTAL_FEE
WHERE CAR_ID NOT IN (
    SELECT CAR_ID
    FROM RENTING_CAR
)
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC