WITH BEST_REST AS (
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
        rank() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) as `RANK`
    FROM REST_INFO
)
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM BEST_REST
WHERE `RANK` = 1
ORDER BY FOOD_TYPE DESC;