SELECT DISTINCT u.USER_ID, u.NICKNAME, 
    CONCAT_WS(' ', u.CITY, u.STREET_ADDRESS1, u.STREET_ADDRESS2) AS 전체주소,
    CONCAT_WS('-', LEFT(u.TLNO, 3), SUBSTRING(u.TLNO, 4, 4), RIGHT(u.TLNO, 4)) AS 전화번호
FROM USED_GOODS_USER u
    INNER JOIN (
        SELECT WRITER_ID
        FROM USED_GOODS_BOARD
        GROUP BY WRITER_ID
        HAVING COUNT(*) >= 3
) board ON u.USER_ID = board.WRITER_ID
ORDER BY u.USER_ID DESC;
