WITH RECURSIVE hirachy AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT e.ID, e.PARENT_ID, h.GENERATION + 1
    FROM ECOLI_DATA e
        INNER JOIN hirachy h
        ON e.PARENT_ID = h.ID
),
children AS (
    SELECT p.ID, COUNT(c.ID) AS CHILDREN_COUNT
    FROM ECOLI_DATA p
        LEFT JOIN ECOLI_DATA c
        ON p.ID = c.PARENT_ID
    GROUP BY p.ID
)
SELECT COUNT(*) AS `COUNT`,
    h.GENERATION
FROM hirachy h
    INNER JOIN children c
    ON h.ID = C.ID
WHERE c.CHILDREN_COUNT = 0
GROUP BY h.GENERATION
ORDER BY h.GENERATION;
