WITH BASE_DATE AS (
    SELECT '2022-10-16' AS TARGET_DATE
)
SELECT DISTINCT h.CAR_ID,
    CASE
        WHEN i.CAR_ID IS NULL THEN '대여 가능'
        ELSE '대여중'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    LEFT JOIN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= (SELECT TARGET_DATE FROM BASE_DATE)
            AND END_DATE >= (SELECT TARGET_DATE FROM BASE_DATE)
    ) i
    ON h.CAR_ID = i.CAR_ID
ORDER BY h.CAR_ID DESC;
        