WITH YEAR_SCORE AS (
    SELECT EMP_NO, SUM(SCORE) / 2 AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT e.EMP_NO, e.EMP_NAME,
    CASE
        WHEN g.SCORE >= 96 THEN 'S'
        WHEN g.SCORE BETWEEN 90 AND 96 THEN 'A'
        WHEN g.SCORE BETWEEN 80 AND 90 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    (CASE
        WHEN g.SCORE >= 96 THEN 0.2
        WHEN g.SCORE BETWEEN 90 AND 96 THEN 0.15
        WHEN g.SCORE BETWEEN 80 AND 90 THEN 0.1
        ELSE 0
    END) * SAL AS BONUS
FROM HR_EMPLOYEES e
    INNER JOIN YEAR_SCORE g
    ON e.EMP_NO = g.EMP_NO
ORDER BY e.EMP_NO ASC;