SELECT ia.ITEM_ID, ia.ITEM_NAME, ia.RARITY
FROM ITEM_TREE t
    INNER JOIN ITEM_INFO ia ON t.ITEM_ID = ia.ITEM_ID
    INNER JOIN ITEM_INFO ib ON t.PARENT_ITEM_ID = ib.ITEM_ID
WHERE ib.RARITY = 'RARE'
ORDER BY ia.ITEM_ID DESC;