WITH VIEWS_RANK AS (
    SELECT BOARD_ID,
        RANK() OVER (ORDER BY VIEWS DESC) AS rk
    FROM USED_GOODS_BOARD
)
SELECT CONCAT('/home/grep/src/', f.BOARD_ID, '/', f.FILE_ID, f.FILE_NAME, f.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE f
    INNER JOIN VIEWS_RANK v
    ON f.BOARD_ID = v.BOARD_ID
        AND v.rk = 1
ORDER BY f.FILE_ID DESC;