SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT p
WHERE CATEGORY IN ('과자', '국', '김치', '식용유') AND 
    p.PRICE = (
        SELECT MAX(c.PRICE)
        FROM FOOD_PRODUCT c
        GROUP BY c.CATEGORY
        HAVING p.CATEGORY = c.CATEGORY
    )
ORDER BY PRICE DESC;
