WITH FRONT_END AS (
    SELECT SUM(`CODE`) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
PYTHON AS (
    SELECT `CODE`
    FROM SKILLCODES
    WHERE NAME = 'Python'
),
C_SHARP AS (
    SELECT `CODE`
    FROM SKILLCODES
    WHERE NAME = 'C#'
)
SELECT CASE
    WHEN SKILL_CODE & (SELECT `CODE` FROM FRONT_END) != 0
        AND SKILL_CODE & (SELECT `CODE` FROM PYTHON) != 0
        THEN 'A'
    WHEN SKILL_CODE & (SELECT `CODE` FROM C_SHARP) != 0
        THEN 'B'
    WHEN SKILL_CODE & (SELECT `CODE` FROM FRONT_END) != 0
        THEN 'C'
END AS GRADE, ID, EMAIL
FROM DEVELOPERS
WHERE CASE
    WHEN SKILL_CODE & (SELECT `CODE` FROM FRONT_END) != 0
        AND SKILL_CODE & (SELECT `CODE` FROM PYTHON) != 0
        THEN 'A'
    WHEN SKILL_CODE & (SELECT `CODE` FROM C_SHARP) != 0
        THEN 'B'
    WHEN SKILL_CODE & (SELECT `CODE` FROM FRONT_END) != 0
        THEN 'C'
END IS NOT NULL
ORDER BY GRADE ASC, ID ASC;
